# M1DIS Star Configuration File
# This file can be passed to m1dis_star.jl using the --config option.
# Example: julia bin/m1dis_star.jl --config star_config.toml
# Any command-line arguments explicitly passed will override the settings here.

# ==============================================================================
# Model Output Parameters 
# ==============================================================================

# Name of the model to save (will be created if empty)
model_name = ""

# Output directory for the saved models (defaults to M1DIS.jl/models/)
out_dir = "models"

# ==============================================================================
# Model Parameters
# ==============================================================================

# Effective temperature [K]
teff = 5777.0

# Surface gravity [log10(g)]
logg = 4.44

# Mixing length parameter
alpha_MLT = 1.5

# ==============================================================================
# Chemical composition
# ==============================================================================

# metallicity
feh = 0.0

# abundance of each element. All elements missing are set to the default values
# which are specified in the abund file (see eos config toml file).
# specify [X/Fe] composition here as e.g. "C_0.3O,O_0.2,Si_-0.3"
composition = ""

# abundance of alpha elements
alpha = 0.0

# Microturbulence velocity (for opacities only) [km/s]
vmic = 1.0

# config file for other opacity table related parameters
eos_config = "eos_config.toml"

# ==============================================================================
# EoS & Opacity Treatment
# ==============================================================================

# Path to the directory containing the Equation of State and Opacity table files. 
# Leave blank if you want to compute the EoS dynamically
#eos_dir = "/mnt/beegfs/gemini/groups/bergemann/users/eitner/storage/opacity_tables/magg_m0_a0_vmic1_v3.5/"
eos_dir = ""

# Signal that the opacity table uses binned opacities (only if eos_dir!="")
binned = false

# Ignore source function from the opacity table and recompute it on-the-fly
mini = true

# Use multi-threading for the Radiative Transfer (RT)
use_threads = true

# include scattering opacity separately from true absorption opacity
scattering = false

# ==============================================================================
# Optical depth grid
# ==============================================================================

# Minimum optical depth to compute
tau_min = -6.0

# Maximum optical depth to compute
tau_max = 2.0

# Number of optical depth points
n_tau = 100

# ==============================================================================
# Solver Parameters (Optional)
# ==============================================================================

# Maximum number of iterations for the solver
maxiter = 200

# Damping parameter for the temperature updates
damping = 0.01
